; PlatformIO Project Configuration File

[common]
platform = espressif32
board = m5stack-cores3
framework = arduino
upload_port = cores3-robot.local
upload_protocol = espota
monitor_port = COM4
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
board_build.extra_flags =
    -DBOARD_HAS_PSRAM
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv

[env:m5stack-cores3]
extends = common
build_flags =
    ${common.build_flags}
    -DENABLE_VOICE_CHAT
lib_deps =
    m5stack/M5CoreS3@^1.0.0
    m5stack/M5Unified@^0.2.2
    mathieucarbou/ESPAsyncWebServer@^3.3.12
    mathieucarbou/AsyncTCP@^3.3.2
    madhephaestus/ESP32Servo@^3.0.5
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    bblanchon/ArduinoJson@^7
build_src_filter = +<main.cpp> +<face.h> +<camera_detect.h> +<expressions.h> +<wifi_config.h> +<servo_ctrl.h> +<voice_chat.h> +<gemini_config.h>

[env:servo-test]
extends = common
lib_deps =
    m5stack/M5CoreS3@^1.0.0
    m5stack/M5Unified@^0.2.2
    madhephaestus/ESP32Servo@^3.0.5
build_src_filter = +<servo_test.cpp> +<wifi_config.h>

[env:pca9685-test]
extends = common
upload_protocol = esptool
upload_port = COM4
lib_deps =
    m5stack/M5CoreS3@^1.0.0
    m5stack/M5Unified@^0.2.2
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
build_src_filter = +<pca9685_test.cpp> +<wifi_config.h>
